### PR TITLE
Add Surjeet Profile

### PR DESCRIPTION
**Pull request by surjeetkhurana**

### CODE REVIEW

**Review by sojinoh93 — CHANGES_REQUESTED** [review]
Hi Surjeet!
You skipped to modify a "profile/ml/ml.md".
Add your name and your profile link.

**Comment by powerstrong** [comment]
> Hi Surjeet! You skipped to modify a "profile/ml/ml.md". Add your name and your profile link.

날카로운 리뷰 좋았습니다 소진님 👍

**Review by powerstrong — APPROVED** [review]
Welcome to PLAiF, Surjeet! 😊

**Comment by wlgjs8** [comment]
Congratulations on joining the PLAIF :)

**Review by wlgjs8 — APPROVED** [review]

**Comment by gunjae-yoon** [comment]
Welcome aboard, Suljit! I'm thrilled to have you as a member of PLAiF and excited to see the impact you'll bring to us.

**Review by gayounghan — APPROVED** [review]
Welcome, Surjeet!
I'm looking forward to seeing your emoji updated on the [Team ML Members](profile/ml/ml.md) list.

**Review by sojinoh93 — APPROVED** [review]

**Pull request merged**
