### PR TITLE
docs(introduction): Revise English self-introduction instructions

### PR DESCRIPTION
**Pull request by eforgacs**
Fix a few minor English-related issues in the instructions.

### CODE REVIEW

**Review by gunjae-yoon — APPROVED** [review]
LGTM :smile: 
Finally, we got a special editor about English!!

**Comment by eforgacs** [comment]
> LGTM 😄 Finally, we got a special editor about English!!

I'm glad to have been of service!

**Review by jongwooparkk — APPROVED** [review]
wow~ very good!!!

**Comment by eforgacs** [comment]
Thanks for the approval, everyone! Barring any objections, I'm going to merge this pull request. 감사합니다!

**Pull request merged**
